ModuleThatProducesLotsOfDiagnostics DEFINITIONS ::= BEGIN

-- DIAG_CODE_IMPORT_SYMBOL_DUP
-- DIAG_CODE_IMPORT_SYMBOL_UNUSED
-- DIAG_CODE_ASSIGNMENT_DUP
-- DIAG_CODE_NAMED_NUM_OR_BIT_DUP
-- DIAG_CODE_NAMED_BIT_OR_ENUM_NEG
-- DIAG_CODE_ENUM_NUM_DUP
-- DIAG_CODE_COMPS_OF_NOT_TYPE
-- DIAG_CODE_COMPS_OF_WRONG_TYPE
-- DIAG_CODE_SET_OR_SEQ_COMP_DUP
-- DIAG_CODE_CHOICE_ALT_DUP
-- DIAG_CODE_SHORT_OID
-- DIAG_CODE_OID_ROOT_ARC_NUM
-- DIAG_CODE_OID_ROOT_ARC_NAME
-- DIAG_CODE_OID_ROOT_ARC_MISMATCH
-- DIAG_CODE_OID_BIG_SECOND_ARC
-- DIAG_CODE_DATE_INVALID
-- DIAG_CODE_DATE_DAY_INVALID
-- DIAG_CODE_TIME_OF_DAY_INVALID
-- DIAG_CODE_DATETIME_INVALID
-- DIAG_CODE_DURATION_NO_P
-- DIAG_CODE_VAL_ASSN_TYPE_NOT_TYPE
-- DIAG_CODE_SYMBOL_NOT_DEFINED
-- DIAG_CODE_EXPORT_NOT_DEFINED
-- DIAG_CODE_LEX_ERROR
-- DIAG_CODE_PARSE_ERROR
-- DIAG_CODE_GROK_ERROR
-- DIAG_CODE_DIAG_DISABLED
-- DIAG_CODE_PROHIBITED_CHAR
-- DIAG_CODE_PARAM_SYMBOL_UNUSED
-- DIAG_CODE_IMPORT_MODULE_DUP

END