# Copied, then modified, from: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
name: Main

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 26.x
    - name: Get Version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
    - name: Install Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run Unit Tests
      run: npm test
      if: runner.os != 'Linux'
    # This is just a test to make sure the command works.
    - name: Generate SBOM
      run: npm sbom --sbom-format=cyclonedx --sbom-type=application > wildboar-asn1.cdx.json
    - name: Install vsce
      run: npm install --no-save @vscode/vsce
    # This is just a test to make sure the command works.
    - name: Create package
      run: npx @vscode/vsce package
