# Copied, then modified, from: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 26.x
    - name: Install Dependencies
      run: npm ci
    - name: Run Unit Tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run Unit Tests
      run: npm test
      if: runner.os != 'Linux'
    # This is just a test to make sure the command works.
    - name: Generate SBOM
      run: npm sbom --sbom-format=cyclonedx --sbom-type=application > extension.cdx.json
    - name: Install vsce
      run: npm install --no-save @vscode/vsce
    # This is just a test to make sure the command works.
    - name: Create package
      run: npx @vscode/vsce package
